services:
  - docker
  - redis-server


matrix:
  allow_failures:
    - python: 3.7-dev

  include:
    - os: linux
      dist: trusty
      language: python
      python: 3.5
      env: BUILD=test

    - os: linux
      dist: trusty
      language: python
      python: 3.6
      env: COVERALLS=yes

    - os: linux
      dist: trusty
      language: python
      python: 3.7-dev
      env: BUILD=test


install:
  - .ci/travis-install.sh

script:
  - .ci/travis-test.sh

deploy:
    provider: script
    script: .ci/travis-release.sh
    on:
        tags: true
        condition: '"${BUILD}" == *release*'


notifications:
  email: false
