language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse unittest2; fi 
  - pip install --use-mirrors cython
  - pip install --use-mirrors http-parser
  - pip install --use-mirrors python-stdnet
  - python setup.py install
  - sudo rm -rf pulsar
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script: python -m runtests --profile --verbosity 2 -w 2 -e taskqueue.redis apps.pubsub.redis --show-leaks --test-timeout 60

branches:
  only:
    - master
    - dev
