language: python

sudo: false

python:
  - 3.5.2
  - nightly

services:
  - redis-server

install:
  - pip install -r requirements-dev.txt

script:
  - python setup.py test --coverage -q
  - flake8
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.2 ]]; then python setup.py test --coveralls; fi
  - python setup.py bench

notifications:
  email: false
