language: python

python:
  - "3.4"

services:
  - redis-server

install:
  - then pip install -r requirements_dev.txt
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

services:
  - redis-server

script:
  - python -m covrun --pep8 pulsar examples tests
  - sudo rm -rf pulsar
  - python -m covrun
  - python -m runtests --coveralls

notifications:
  email: false

branches:
  only:
    - master
    - dev
