language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

services:
  - redis-server

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install -r requirements_dev_27.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install -r requirements_dev_27.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then pip install -r requirements_dev_33.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -r requirements_dev.txt; fi
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

services:
  - redis-server
  - mongodb

script:
  - python -m covrun --pep8 pulsar examples tests
  - sudo rm -rf pulsar
  - python -m covrun -w 2 -e pshell webmail stores.query stores.odm.couchdb stores.odm.redis stores.couchdb stores.redis
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then python -m runtests --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
    - dev
