language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse unittest2; fi
  - pip install -r requirements_dev.txt --use-mirrors
  - python setup.py install
  - sudo rm -rf pulsar
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
script:
  coverage run -p runtests.py -w 2 --test-timeout 60 --coverage --profile

after_success:
  coverage combine
  coveralls

branches:
  only:
    - master
    - dev
