language: python

python:
  - 3.5.2
  - 3.6-dev

services:
  - redis-server

install:
  - sudo apt-get install enchant
  - pip install -r requirements-dev.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.2 ]]; then pip install uvloop; fi

script:
  - python -W ignore setup.py test --coverage -q
  - flake8
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.2 ]]; then python setup.py test --coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.2 ]]; then python setup.py test -q --io uv; fi
  - python -W ignore setup.py test --http-py-parser -q
  - python setup.py bench
  # - python setup.py bench --io uv
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.2 ]]; then cd docs && make spelling; fi


notifications:
  email: false
