language: generic

osx_image: xcode9.1

branches:
  only:
  - release

env:
    global:
        - PYMODULE=pulsar
        - WHEEL=macosx

matrix:
    fast_finish: true

    include:
        - os: osx
          env: PYTHON_VERSION=3.5.4

        - os: osx
          env: PYTHON_VERSION=3.6.3

install:
    - ci/mac-pre-install.sh
    - ci/install.sh

script:
    - make pypi-check
    - make wheels
    - make uploadwheels
