language: python

python:
  - "2.7"
  - "3.3"
  - "pypy"

services:
  - redis-server

install:
  - pip install -r requirements_dev.txt --use-mirrors
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

services:
  - redis-server

script:
  - python -m covrun --pep8
  - sudo rm -rf pulsar
  - python -m covrun -w 2 -e taskqueue shell philosophers echo chat

notifications:
  email: false

branches:
  only:
    - master
    - dev
