language: python

sudo: false

python:
  - 3.5.1

services:
  - redis-server

install:
  - pip install -r requirements-dev.txt
  - python setup.py egg_info

services:
  - redis-server

script:
  - python setup.py flake8
  - python setup.py test --coverage
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.1 ]]; then python setup.py test --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
    - dev
