language: generic

osx_image: xcode9.1

env:
    global:
        - PYMODULE=pulsar
        - PYTHON=python
        - PIP=pip
        - WHEEL=macosx
        - IOPATH=/

matrix:
    fast_finish: true

    include:
        - os: osx
          env: PYTHON_VERSION=3.5.4
          branches:
              only:
                  - deploy

        - os: osx
          env: PYTHON_VERSION=3.6.3
          branches:
              only:
                  - deploy

install:
    - ci/mac-install.sh

script:
    - make wheels
    - make uploadwheels
