language: generic


services:
  - docker
  - redis-server


env:
  global:
    - PYMODULE=pulsar


matrix:
  allow_failures:
    - python: 3.7-dev

  include:
    - os: linux
      dist: trusty
      language: python
      python: 3.5.4
      env: BUILD=tests

    - os: linux
      dist: trusty
      language: python
      python: 3.6.3
      env: BUILD=tests COVERALLS=yes

    - os: linux
      dist: trusty
      language: python
      python: 3.7-dev
      env: BUILD=tests


cache:
    pip

install:
  - .ci/travis-install.sh

script:
  - .ci/travis-test.sh && .ci/travis-build-wheels.sh

deploy:
    provider: script
    script: .ci/travis-release.sh
    on:
        tags: true
        condition: '"${BUILD}" == *release*'


notifications:
  email: false
