language: python

python:
  - "3.4"

services:
  - redis-server

install:
  - pip install -r requirements_dev.txt
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

services:
  - redis-server

script:
  - flake8
  - sudo rm -rf pulsar
  - python -m runtests --coverage
  - python -m runtests --coveralls

notifications:
  email: false

branches:
  only:
    - master
    - dev
