language: python

sudo: false

python:
  - 3.5.1

services:
  - redis-server

install:
  - pip install -r requirements-dev.txt
  - python setup.py egg_info

script:
  - flake8
  - coverage run setup.py test --coverage --log-level error --verbosity 2
  - coverage combine
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.1 ]]; then python setup.py test --coveralls; fi

notifications:
  email: false

branches:
  only:
    - master
    - dev
