language: generic

osx_image: xcode9.1

branches:
  only:
  - deploy

env:
    global:
        - PYMODULE=pulsar
        - PYTHON=python
        - PIP=pip
        - WHEEL=macosx
        - IOPATH=/

matrix:
    fast_finish: true

    include:
        - os: osx
          env: PYTHON_VERSION=3.5.4

        - os: osx
          env: PYTHON_VERSION=3.6.3

install:
    - ci/mac-install.sh

script:
    - make wheels
    - make uploadwheels
