language: python

python:
  - 3.5.2
  - 3.6.0
  - 3.7-dev

matrix:
  allow_failures:
    - python: 3.7-dev

env:
  - COVERAGE=3.6.0

services:
  - redis-server

install:
  - .ci/travis-install.sh

script:
  - .ci/travis-test.sh


notifications:
  email: false
