version: 2
jobs:
    build-main:
        working_directory: ~/pulsar-current
        docker:
          - image: python:3.6.3
          - image: redis
        steps:
          - checkout
          - run:
              name: install packages
              command: ci/install.sh
          - run:
              name: test
              command: make compile && make test
    build-coverage:
        working_directory: ~/pulsar-coverage
        docker:
          - image: python:3.6.3
          - image: redis
        steps:
          - checkout
          - run:
              name: install packages
              command: ci/install.sh
          - run:
              name: run and publish coverage
              command: make coverage && codecov
    build-lagacy:
        working_directory: ~/pulsar-legacy
        docker:
          - image: python:3.5.4
          - image: redis
        steps:
          - checkout
          - run:
              name: install packages
              command: ci/install.sh
          - run:
              name: test
              command: make compile && make test
    deploy:
        docker:
            working_directory: ~/pulsar-deploy
        docker:
          - image: quay.io/pypa/manylinux1_x86_64
        steps:
          - checkout

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-main
      - build-coverage
      - build-lagacy
      - deploy:
          requires:
            - build-main
          filters:
            branches:
              only: deploy
